services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx_reverse_proxy
    ports:
      - "80:80"
    volumes:
      - ./conf.d/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - my_network

networks:
  my_network:
    external: true
